#PBS -N MicrobeAnnotorDB
#PBS -l nodes=1:ppn=2
#PBS -l mem=15gb
#PBS -l walltime=6:00:00
#PBS -q inferno     
#PBS -A GT-ktk3-CODA20
#PBS -o 00a_log/MicrobeAnnotatorDB_${n}.out
#PBS -e 00a_log/MicrobeAnnotatorDB_${n}.err

module purge

source activate genome_diversity

cd $PBS_O_WORKDIR

database=/storage/home/hcoda1/9/rconrad6/p-ktk3-0/apps/MicrobeAnnotator/MicrobeAnnotator_DB
microbeannotator=/storage/home/hcoda1/9/rconrad6/p-ktk3-0/apps/MicrobeAnnotator/microbeannotator.py

python ${microbeannotator} -i ${input} -o ${outdir}/${n} -m diamond -d ${database} -p 2

## NOTE -p specifies ppn per fasta file.

## Run Log:
## qsub -v input=,outdir=,n= ../00_PBS/04_MicrobeAnnotator_Annotate.pbs
## for f in 03a_PredictedGenes/*faa; do n=`basename $f | cut -d. -f1`; qsub -v input=${f},output=03b_AnnotatedGenes/${n},n=${n} ../00b_PBS/08a_MicrobeAnnotator.pbs; done
